# Generated by Django 4.2.4 on 2024-04-06 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trivia_game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=20)),
                ('initial_time', models.DateTimeField(auto_now_add=True)),
                ('final_time', models.DurationField(blank=True, null=True)),
                ('successes', models.PositiveIntegerField(default=0)),
                ('answered_questions', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
