# Generated by Django 4.2.4 on 2024-04-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia_game',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
