# Generated by Django 4.2.4 on 2024-04-30 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_game', '0002_trivia_game_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia_game',
            name='answered_questions',
        ),
        migrations.RemoveField(
            model_name='trivia_game',
            name='final_time',
        ),
    ]
