# Generated by Django 4.2.4 on 2024-03-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='data_api',
            field=models.JSONField(default=None),
        ),
    ]
