# Generated by Django 4.2.4 on 2024-03-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_trivia_data_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='preguntas_contestadas',
            field=models.IntegerField(default=-1),
        ),
    ]
