# Generated by Django 4.2.4 on 2024-03-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_trivia_preguntas_contestadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='preguntas_contestadas',
            field=models.IntegerField(default=0),
        ),
    ]
