# Generated by Django 4.2.4 on 2024-03-07 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_alter_trivia_preguntas_contestadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.categorias'),
        ),
    ]
